# Puerto en que escucha Spring Boot
server.port=8080

# Servicio de la base de datos.
# Ejemplo url base dator: 
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:192.168.1.36}:${DB_PORT:3306}/${DB_NAME:ministerio}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:postgresql_123}

# Parámetros del Pool de conexiones HikariCP
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2